"""
This type stub file was generated by pyright.
"""

import warnings
from .manage_plugins import *
from .manage_plugins import _hide_plugin_deprecation_warnings
from .sift import *
from .collection import *
from ._io import *
from ._image_stack import *

"""Reading and saving of images and videos."""
__all__ = ["concatenate_images", "imread", "imread_collection", "imread_collection_wrapper", "imsave", "load_sift", "load_surf", "pop", "push", "ImageCollection", "MultiImage"]
def __getattr__(name) -> Any:
    ...

