"""
This type stub file was generated by pyright.
"""

__all__ = ['image_stack', 'push', 'pop']
image_stack = ...
def push(img) -> None:
    """Push an image onto the shared image stack.

    Parameters
    ----------
    img : ndarray
        Image to push.

    """
    ...

def pop():
    """Pop an image from the shared image stack.

    Returns
    -------
    img : ndarray
        Image popped from the stack.

    """
    ...

