"""
This type stub file was generated by pyright.
"""

from .._shared.utils import deprecate_func, deprecate_parameter
from .._shared.version_requirements import require

__all__ = ['imread', 'imsave', 'imshow', 'show', 'imread_collection', 'imshow_collection']
_remove_plugin_param_template = ...
@deprecate_parameter("plugin", start_version="0.25", stop_version="0.27", template=_remove_plugin_param_template)
def imread(fname, as_gray=..., plugin=..., **plugin_args):
    """Load an image from file.

    Parameters
    ----------
    fname : str or pathlib.Path
        Image file name, e.g. ``test.jpg`` or URL.
    as_gray : bool, optional
        If True, convert color images to gray-scale (64-bit floats).
        Images that are already in gray-scale format are not converted.

    Other Parameters
    ----------------
    plugin_args : DEPRECATED
        The plugin infrastructure is deprecated.

    Returns
    -------
    img_array : ndarray
        The different color bands/channels are stored in the
        third dimension, such that a gray-image is MxN, an
        RGB-image MxNx3 and an RGBA-image MxNx4.

    """
    ...

@deprecate_parameter("plugin", start_version="0.25", stop_version="0.27", template=_remove_plugin_param_template)
def imread_collection(load_pattern, conserve_memory=..., plugin=..., **plugin_args):
    """
    Load a collection of images.

    Parameters
    ----------
    load_pattern : str or list
        List of objects to load. These are usually filenames, but may
        vary depending on the currently active plugin. See :class:`ImageCollection`
        for the default behaviour of this parameter.
    conserve_memory : bool, optional
        If True, never keep more than one in memory at a specific
        time.  Otherwise, images will be cached once they are loaded.

    Returns
    -------
    ic : :class:`ImageCollection`
        Collection of images.

    Other Parameters
    ----------------
    plugin_args : DEPRECATED
        The plugin infrastructure is deprecated.

    """
    ...

@deprecate_parameter("plugin", start_version="0.25", stop_version="0.27", template=_remove_plugin_param_template)
def imsave(fname, arr, plugin=..., *, check_contrast=..., **plugin_args):
    """Save an image to file.

    Parameters
    ----------
    fname : str or pathlib.Path
        Target filename.
    arr : ndarray of shape (M,N) or (M,N,3) or (M,N,4)
        Image data.
    check_contrast : bool, optional
        Check for low contrast and print warning (default: True).

    Other Parameters
    ----------------
    plugin_args : DEPRECATED
        The plugin infrastructure is deprecated.
    """
    ...

@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="Please use `matplotlib`, `napari`, etc. to visualize images.")
def imshow(arr, plugin=..., **plugin_args):
    """Display an image.

    Parameters
    ----------
    arr : ndarray or str
        Image data or name of image file.
    plugin : str
        Name of plugin to use.  By default, the different plugins are
        tried (starting with imageio) until a suitable candidate is found.

    Other Parameters
    ----------------
    plugin_args : keywords
        Passed to the given plugin.

    """
    ...

@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="Please use `matplotlib`, `napari`, etc. to visualize images.")
def imshow_collection(ic, plugin=..., **plugin_args):
    """Display a collection of images.

    Parameters
    ----------
    ic : :class:`ImageCollection`
        Collection to display.

    Other Parameters
    ----------------
    plugin_args : keywords
        Passed to the given plugin.

    """
    ...

@require("matplotlib", ">=3.3")
@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="Please use `matplotlib`, `napari`, etc. to visualize images.")
def show():
    """Display pending images.

    Launch the event loop of the current GUI plugin, and display all
    pending images, queued via `imshow`. This is required when using
    `imshow` from non-interactive scripts.

    A call to `show` will block execution of code until all windows
    have been closed.

    Examples
    --------
    >>> import skimage.io as io
    >>> rng = np.random.default_rng()
    >>> for i in range(4):
    ...     ax_im = io.imshow(rng.random((50, 50)))  # doctest: +SKIP
    >>> io.show() # doctest: +SKIP

    """
    ...

