"""
This type stub file was generated by pyright.
"""

from .._shared.utils import deprecate_func

"""Handle image reading, writing and plotting plugins.

To improve performance, plugins are only loaded as needed. As a result, there
can be multiple states for a given plugin:

    available: Defined in an *ini file located in ``skimage.io._plugins``.
        See also :func:`skimage.io.available_plugins`.
    partial definition: Specified in an *ini file, but not defined in the
        corresponding plugin module. This will raise an error when loaded.
    available but not on this system: Defined in ``skimage.io._plugins``, but
        a dependent library (e.g. Qt, PIL) is not available on your system.
        This will raise an error when loaded.
    loaded: The real availability is determined when it's explicitly loaded,
        either because it's one of the default plugins, or because it's
        loaded explicitly by the user.

"""
__all__ = ['use_plugin', 'call_plugin', 'plugin_info', 'plugin_order', 'reset_plugins', 'find_available_plugins', '_available_plugins']
plugin_store = ...
plugin_provides = ...
plugin_module_name = ...
plugin_meta_data = ...
preferred_plugins = ...
@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="The plugin infrastructure of `skimage.io` is deprecated. " "Instead, use `imageio` or other I/O packages directly.")
def reset_plugins() -> None:
    ...

@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="The plugin infrastructure of `skimage.io` is deprecated. " "Instead, use `imageio` or other I/O packages directly.")
def find_available_plugins(loaded=...) -> dict[Any, Any]:
    """List available plugins.

    Parameters
    ----------
    loaded : bool
        If True, show only those plugins currently loaded.  By default,
        all plugins are shown.

    Returns
    -------
    p : dict
        Dictionary with plugin names as keys and exposed functions as
        values.

    """
    ...

@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="The plugin infrastructure of `skimage.io` is deprecated. " "Instead, use `imageio` or other I/O packages directly.")
def call_plugin(kind, *args, **kwargs):
    """Find the appropriate plugin of 'kind' and execute it.

    Parameters
    ----------
    kind : {'imshow', 'imsave', 'imread', 'imread_collection'}
        Function to look up.
    plugin : str, optional
        Plugin to load.  Defaults to None, in which case the first
        matching plugin is used.
    *args, **kwargs : arguments and keyword arguments
        Passed to the plugin function.

    """
    ...

@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="The plugin infrastructure of `skimage.io` is deprecated. " "Instead, use `imageio` or other I/O packages directly.")
def use_plugin(name, kind=...) -> None:
    """Set the default plugin for a specified operation.  The plugin
    will be loaded if it hasn't been already.

    Parameters
    ----------
    name : str
        Name of plugin. See ``skimage.io.available_plugins`` for a list of available
        plugins.
    kind : {'imsave', 'imread', 'imshow', 'imread_collection', 'imshow_collection'}, optional
        Set the plugin for this function.  By default,
        the plugin is set for all functions.

    Examples
    --------
    To use Matplotlib as the default image reader, you would write:

    >>> from skimage import io
    >>> io.use_plugin('matplotlib', 'imread')  # doctest: +SKIP

    To see a list of available plugins run ``skimage.io.available_plugins``. Note
    that this lists plugins that are defined, but the full list may not be usable
    if your system does not have the required libraries installed.

    """
    ...

@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="The plugin infrastructure of `skimage.io` is deprecated. " "Instead, use `imageio` or other I/O packages directly.")
def plugin_info(plugin):
    """Return plugin meta-data.

    Parameters
    ----------
    plugin : str
        Name of plugin.

    Returns
    -------
    m : dict
        Meta data as specified in plugin ``.ini``.

    """
    ...

@deprecate_func(deprecated_version="0.25", removed_version="0.27", hint="The plugin infrastructure of `skimage.io` is deprecated. " "Instead, use `imageio` or other I/O packages directly.")
def plugin_order() -> dict[Any, Any]:
    """Return the currently preferred plugin order.

    Returns
    -------
    p : dict
        Dictionary of preferred plugin order, with function name as key and
        plugins (in order of preference) as value.

    """
    ...

