"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Protocol, Self, runtime_checkable
from .._shared.utils import FailedEstimation, _deprecate_estimate, deprecate_func

_EPSILON = np.spacing(1)
@runtime_checkable
class RansacModelProtocol(Protocol):
    """Protocol for `ransac` model class."""
    @classmethod
    def from_estimate(cls, *data) -> None:
        ...
    
    def residuals(self, *data) -> None:
        ...
    


_PARAMS_DEP_START = ...
_PARAMS_DEP_STOP = ...
class BaseModel:
    def __init_subclass__(self) -> None:
        ...
    


class _BaseModel:
    """Implement common methods for model classes.

    This class can be removed when we expire deprecations of ``estimate``
    method, and `params` arguments to ``predict*`` methods.

    Note that each inheriting class will need to implement
    ``_params2init_values``, that breaks up the ``params`` vector into separate
    components comprising the arguments to the function ``__init__``, and
    checks the resulting input arguments for validity.
    """
    @classmethod
    def from_estimate(cls, data) -> Self | FailedEstimation:
        ...
    


@_deprecate_no_args
class LineModelND(_BaseModel):
    """Total least squares estimator for N-dimensional lines.

    In contrast to ordinary least squares line estimation, this estimator
    minimizes the orthogonal distances of points to the estimated line.

    Lines are defined by a point (origin) and a unit vector (direction)
    according to the following vector equation::

        X = origin + lambda * direction

    Parameters
    ----------
    origin : array-like, shape (N,)
        Coordinates of line origin in N dimensions.
    direction : array-like, shape (N,)
        Vector giving line direction.

    Raises
    ------
    ValueError
        If length of `origin` and `direction` differ.

    Examples
    --------
    >>> x = np.linspace(1, 2, 25)
    >>> y = 1.5 * x + 3
    >>> lm = LineModelND.from_estimate(np.stack([x, y], axis=-1))
    >>> lm.origin
    array([1.5 , 5.25])
    >>> lm.direction  # doctest: +FLOAT_CMP
    array([0.5547 , 0.83205])
    >>> res = lm.residuals(np.stack([x, y], axis=-1))
    >>> np.abs(np.round(res, 9))
    array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0.])
    >>> np.round(lm.predict_y(x[:5]), 3)
    array([4.5  , 4.562, 4.625, 4.688, 4.75 ])
    >>> np.round(lm.predict_x(y[:5]), 3)
    array([1.   , 1.042, 1.083, 1.125, 1.167])

    """
    @property
    @deprecate_func(deprecated_version=_PARAMS_DEP_START, removed_version=_PARAMS_DEP_STOP, hint='`params` attribute deprecated; use ``origin, direction`` attributes instead')
    def params(self) -> tuple[NDArray[Any] | Any, NDArray[Any] | Any]:
        """Return model attributes as ``origin, direction`` tuple."""
        ...
    
    @classmethod
    def from_estimate(cls, data) -> Self | FailedEstimation:
        """Estimate line model from data.

        This minimizes the sum of shortest (orthogonal) distances
        from the given data points to the estimated line.

        Parameters
        ----------
        data : (N, dim) array
            N points in a space of dimensionality dim >= 2.

        Returns
        -------
        model : Self or `~.FailedEstimation`
            An instance of the line model if the estimation succeeded.
            Otherwise, we return a special ``FailedEstimation`` object to
            signal a failed estimation. Testing the truth value of the failed
            estimation object will return ``False``. E.g.

            .. code-block:: python

                model = LineModelND.from_estimate(...)
                if not model:
                    raise RuntimeError(f"Failed estimation: {model}")
        """
        ...
    
    @_deprecate_model_params
    def residuals(self, data, params=...):
        """Determine residuals of data to model.

        For each point, the shortest (orthogonal) distance to the line is
        returned. It is obtained by projecting the data onto the line.

        Parameters
        ----------
        data : (N, dim) array
            N points in a space of dimension dim.

        Returns
        -------
        residuals : (N,) array
            Residual for each data point.

        Other parameters
        ----------------
        params : `~.DEPRECATED`, optional
            Optional custom parameter set in the form (`origin`, `direction`).

            .. deprecated:: {{ start_version }}
        """
        ...
    
    @_deprecate_model_params
    def predict(self, x, axis=..., params=...):
        """Predict intersection of line model with orthogonal hyperplane.

        Parameters
        ----------
        x : (n, 1) array
            Coordinates along an axis.
        axis : int
            Axis orthogonal to the hyperplane intersecting the line.

        Returns
        -------
        data : (n, m) array
            Predicted coordinates.

        Other parameters
        ----------------
        params : `~.DEPRECATED`, optional
            Optional custom parameter set in the form (`origin`, `direction`).

            .. deprecated:: {{ start_version }}

        Raises
        ------
        ValueError
            If the line is parallel to the given axis.
        """
        ...
    
    @_deprecate_model_params
    def predict_x(self, y, params=...):
        """Predict x-coordinates for 2D lines using the estimated model.

        Alias for::

            predict(y, axis=1)[:, 0]

        Parameters
        ----------
        y : array
            y-coordinates.

        Returns
        -------
        x : array
            Predicted x-coordinates.

        Other parameters
        ----------------
        params : `~.DEPRECATED`, optional
            Optional custom parameter set in the form (`origin`, `direction`).

            .. deprecated:: {{ start_version }}

        """
        ...
    
    @_deprecate_model_params
    def predict_y(self, x, params=...):
        """Predict y-coordinates for 2D lines using the estimated model.

        Alias for::

            predict(x, axis=0)[:, 1]

        Parameters
        ----------
        x : array
            x-coordinates.

        Returns
        -------
        y : array
            Predicted y-coordinates.

        Other parameters
        ----------------
        params : `~.DEPRECATED`, optional
            Optional custom parameter set in the form (`origin`, `direction`).

            .. deprecated:: {{ start_version }}

        """
        ...
    
    @_deprecate_estimate
    def estimate(self, data) -> bool:
        """Estimate line model from data.

        This minimizes the sum of shortest (orthogonal) distances
        from the given data points to the estimated line.

        Parameters
        ----------
        data : (N, dim) array
            N points in a space of dimensionality ``dim >= 2``.

        Returns
        -------
        success : bool
            True, if model estimation succeeds.
        """
        ...
    


@_deprecate_no_args
class CircleModel(_BaseModel):
    """Total least squares estimator for 2D circles.

    The functional model of the circle is::

        r**2 = (x - xc)**2 + (y - yc)**2

    This estimator minimizes the squared distances from all points to the
    circle::

        min{ sum((r - sqrt((x_i - xc)**2 + (y_i - yc)**2))**2) }

    A minimum number of 3 points is required to solve for the parameters.

    Parameters
    ----------
    center : array-like, shape (2,)
        Coordinates of circle center.
    radius : float
        Circle radius.

    Notes
    -----
    The estimation is carried out using a 2D version of the spherical
    estimation given in [1]_.

    References
    ----------
    .. [1] Jekel, Charles F. Obtaining non-linear orthotropic material models
           for pvc-coated polyester via inverse bubble inflation.
           Thesis (MEng), Stellenbosch University, 2016. Appendix A, pp. 83-87.
           https://hdl.handle.net/10019.1/98627

    Raises
    ------
    ValueError
        If `center` does not have length 2.

    Examples
    --------
    >>> t = np.linspace(0, 2 * np.pi, 25)
    >>> xy = CircleModel((2, 3), 4).predict_xy(t)
    >>> model = CircleModel.from_estimate(xy)
    >>> model.center
    array([2., 3.])
    >>> model.radius
    4.0
    >>> res = model.residuals(xy)
    >>> np.abs(np.round(res, 9))
    array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0.])

    The estimation can fail when — for example — all the input or output
    points are the same.  If this happens, you will get a transform that is not
    "truthy" - meaning that ``bool(tform)`` is ``False``:

    >>> # A successfully estimated model is truthy:
    >>> if model:
    ...     print("Estimation succeeded.")
    Estimation succeeded.
    >>> # Not so for a degenerate model with identical points.
    >>> bad_data = np.ones((4, 2))
    >>> bad_model = CircleModel.from_estimate(bad_data)
    >>> if not bad_model:
    ...     print("Estimation failed.")
    Estimation failed.

    Trying to use this failed estimation transform result will give a suitable
    error:

    >>> bad_model.residuals(xy)  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
      ...
    FailedEstimationAccessError: No attribute "residuals" for failed estimation ...
    """
    @property
    @deprecate_func(deprecated_version=_PARAMS_DEP_START, removed_version=_PARAMS_DEP_STOP, hint='`params` attribute deprecated; use `center, radius` attributes instead')
    def params(self) -> Incomplete:
        """Return model attributes ``center, radius`` as 1D array."""
        ...
    
    @classmethod
    def from_estimate(cls, data) -> Self | FailedEstimation:
        """Estimate circle model from data using total least squares.

        Parameters
        ----------
        data : (N, 2) array
            N points with ``(x, y)`` coordinates, respectively.

        Returns
        -------
        model : Self or `~.FailedEstimation`
            An instance of the circle model if the estimation succeeded.
            Otherwise, we return a special ``FailedEstimation`` object to
            signal a failed estimation. Testing the truth value of the failed
            estimation object will return ``False``. E.g.

            .. code-block:: python

                model = CircleModel.from_estimate(...)
                if not model:
                    raise RuntimeError(f"Failed estimation: {model}")
        """
        ...
    
    def residuals(self, data):
        """Determine residuals of data to model.

        For each point the shortest distance to the circle is returned.

        Parameters
        ----------
        data : (N, 2) array
            N points with ``(x, y)`` coordinates, respectively.

        Returns
        -------
        residuals : (N,) array
            Residual for each data point.

        """
        ...
    
    @_deprecate_model_params
    def predict_xy(self, t, params=...) -> NDArray[Any]:
        """Predict x- and y-coordinates using the estimated model.

        Parameters
        ----------
        t : array-like
            Angles in circle in radians. Angles start to count from positive
            x-axis to positive y-axis in a right-handed system.

        Returns
        -------
        xy : (..., 2) array
            Predicted x- and y-coordinates.

        Other parameters
        ----------------
        params : `~.DEPRECATED`, optional
            Optional parameters ``xc``, ``yc``, `radius`.

            .. deprecated:: {{ start_version }}
        """
        ...
    
    @_deprecate_estimate
    def estimate(self, data) -> bool:
        """Estimate circle model from data using total least squares.

        Parameters
        ----------
        data : (N, 2) array
            N points with ``(x, y)`` coordinates, respectively.

        Returns
        -------
        success : bool
            True, if model estimation succeeds.

        """
        ...
    


@_deprecate_no_args
class EllipseModel(_BaseModel):
    """Total least squares estimator for 2D ellipses.

    The functional model of the ellipse is::

        xt = xc + a*cos(theta)*cos(t) - b*sin(theta)*sin(t)
        yt = yc + a*sin(theta)*cos(t) + b*cos(theta)*sin(t)
        d = sqrt((x - xt)**2 + (y - yt)**2)

    where ``(xt, yt)`` is the closest point on the ellipse to ``(x, y)``. Thus
    d is the shortest distance from the point to the ellipse.

    The estimator is based on a least squares minimization. The optimal
    solution is computed directly, no iterations are required. This leads
    to a simple, stable and robust fitting method.

    Parameters
    ----------
    center : array-like, shape (2,)
        Coordinates of ellipse center.
    axis_lengths : array-like, shape (2,)
        Length of first axis and length of second axis.  Call these ``a`` and
        ``b``.
    theta : float
        Angle of first axis.

    Raises
    ------
    ValueError
        If `center` does not have length 2.

    Examples
    --------

    >>> em = EllipseModel((10, 15), (8, 4), np.deg2rad(30))
    >>> xy = em.predict_xy(np.linspace(0, 2 * np.pi, 25))
    >>> ellipse = EllipseModel.from_estimate(xy)
    >>> ellipse.center
    array([10., 15.])
    >>> ellipse.axis_lengths
    array([8., 4.])
    >>> round(ellipse.theta, 2)
    0.52
    >>> np.round(abs(ellipse.residuals(xy)), 5)
    array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0.])

    The estimation can fail when — for example — all the input or output
    points are the same.  If this happens, you will get an ellipse model for
    which ``bool(model)`` is ``False``:

    >>> # A successfully estimated model is truthy:
    >>> if ellipse:
    ...     print("Estimation succeeded.")
    Estimation succeeded.
    >>> # Not so for a degenerate model with identical points.
    >>> bad_data = np.ones((4, 2))
    >>> bad_ellipse = EllipseModel.from_estimate(bad_data)
    >>> if not bad_ellipse:
    ...     print("Estimation failed.")
    Estimation failed.

    Trying to use this failed estimation transform result will give a suitable
    error:

    >>> bad_ellipse.residuals(xy)  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
      ...
    FailedEstimationAccessError: No attribute "residuals" for failed estimation ...
    """
    @property
    @deprecate_func(deprecated_version=_PARAMS_DEP_START, removed_version=_PARAMS_DEP_STOP, hint='`params` attribute deprecated; use `center, axis_lengths, theta` attributes instead')
    def params(self) -> Incomplete:
        """Return model attributes ``center, axis_lengths, theta`` as 1D array."""
        ...
    
    @classmethod
    def from_estimate(cls, data) -> Self | FailedEstimation:
        """Estimate ellipse model from data using total least squares.

        Parameters
        ----------
        data : (N, 2) array
            N points with ``(x, y)`` coordinates, respectively.

        Returns
        -------
        model : Self or `~.FailedEstimation`
            An instance of the ellipse model if the estimation succeeded.
            Otherwise, we return a special ``FailedEstimation`` object to
            signal a failed estimation. Testing the truth value of the failed
            estimation object will return ``False``. E.g.

            .. code-block:: python

                model = EllipseModel.from_estimate(...)
                if not model:
                    raise RuntimeError(f"Failed estimation: {model}")

        References
        ----------
        .. [1] Halir, R.; Flusser, J. "Numerically stable direct least squares
               fitting of ellipses". In Proc. 6th International Conference in
               Central Europe on Computer Graphics and Visualization.
               WSCG (Vol. 98, pp. 125-132).

        """
        ...
    
    def residuals(self, data) -> _Array[tuple[Any], float64]:
        """Determine residuals of data to model.

        For each point the shortest distance to the ellipse is returned.

        Parameters
        ----------
        data : (N, 2) array
            N points with ``(x, y)`` coordinates, respectively.

        Returns
        -------
        residuals : (N,) array
            Residual for each data point.

        """
        ...
    
    @_deprecate_model_params
    def predict_xy(self, t, params=...) -> NDArray[Any]:
        """Predict x- and y-coordinates using the estimated model.

        Parameters
        ----------
        t : array
            Angles in circle in radians. Angles start to count from positive
            x-axis to positive y-axis in a right-handed system.

        Returns
        -------
        xy : (..., 2) array
            Predicted x- and y-coordinates.

        Other parameters
        ----------------
        params : `~.DEPRECATED`, optional
            Optional ellipse model parameters in the following order ``xc``,
            ``yc``, `a`, `b`, `theta`.

            .. deprecated:: {{ start_version }}
        """
        ...
    
    @_deprecate_estimate
    def estimate(self, data) -> bool:
        """Estimate ellipse model from data using total least squares.

        Parameters
        ----------
        data : (N, 2) array
            N points with ``(x, y)`` coordinates, respectively.

        Returns
        -------
        success : bool
            True, if model estimation succeeds.


        References
        ----------
        .. [1] Halir, R.; Flusser, J. "Numerically stable direct least squares
               fitting of ellipses". In Proc. 6th International Conference in
               Central Europe on Computer Graphics and Visualization.
               WSCG (Vol. 98, pp. 125-132).

        """
        ...
    


def add_from_estimate(cls) -> type[FromEstimated]:
    """Add ``from_estimate`` method  class using ``estimate`` method"""
    class FromEstimated(cls):
        ...
    
    

def ransac(data, model_class, min_samples, residual_threshold, is_data_valid=..., is_model_valid=..., max_trials=..., stop_sample_num=..., stop_residuals_sum=..., stop_probability=..., rng=..., initial_inliers=...) -> tuple[Any | None, Any | list[Any] | None]:
    """Fit a model to data with the RANSAC (random sample consensus) algorithm.

    RANSAC is an iterative algorithm for the robust estimation of parameters
    from a subset of inliers from the complete data set. Each iteration
    performs the following tasks:

    1. Select `min_samples` random samples from the original data and check
       whether the set of data is valid (see `is_data_valid`).
    2. Estimate a model to the random subset
       (`model_cls.from_estimate(*data[random_subset]`) and check whether the
       estimated model is valid (see `is_model_valid`).
    3. Classify all data as inliers or outliers by calculating the residuals
       to the estimated model (`model_cls.residuals(*data)`) - all data samples
       with residuals smaller than the `residual_threshold` are considered as
       inliers.
    4. Save estimated model as best model if number of inlier samples is
       maximal. In case the current estimated model has the same number of
       inliers, it is only considered as the best model if it has less sum of
       residuals.

    These steps are performed either a maximum number of times or until one of
    the special stop criteria are met. The final model is estimated using all
    inlier samples of the previously determined best model.

    Parameters
    ----------
    data : list or tuple or array of shape (N,)
        Data set to which the model is fitted, where N is the number of data
        points and the remaining dimension are depending on model requirements.
        If the model class requires multiple input data arrays (e.g. source and
        destination coordinates of  ``skimage.transform.AffineTransform``),
        they can be optionally passed as tuple or list. Note, that in this case
        the functions ``estimate(*data)``, ``residuals(*data)``,
        ``is_model_valid(model, *random_data)`` and
        ``is_data_valid(*random_data)`` must all take each data array as
        separate arguments.
    model_class : type
        Class with the following methods:

        * Either:

          * ``from_estimate`` class method returning transform instance, as in
            ``tform = model_class.from_estimate(*data)``; the resulting
            ``tform`` should be truthy (``bool(tform) == True``) where
            estimation succeeded, or falsey (``bool(tform) == False``) where it
            failed;  OR
          * (deprecated) ``estimate`` instance method, returning flag to
            indicate successful estimation, as in ``tform = model_class();
            success = tform.estimate(*data)``. ``success == True`` when
            estimation succeeded, ``success == False`` when it failed.

        * ``residuals(*data)``

        Your model should conform to the ``RansacModelProtocol`` — meaning
        implement all of the methods / attributes specified by the
        :class:``RansacModelProctocol``. An easy check to see whether that is
        the case is to use ``isinstance(MyModel, RansacModelProtocol)``. See
        https://docs.python.org/3/library/typing.html#typing.Protocol for more
        details.

    min_samples : int, in range (0, N)
        The minimum number of data points to fit a model to.
    residual_threshold : float, >0
        Maximum distance for a data point to be classified as an inlier.
    is_data_valid : Callable, optional
        This function is called with the randomly selected data before the
        model is fitted to it: `is_data_valid(*random_data)`.
    is_model_valid : Callable, optional
        This function is called with the estimated model and the randomly
        selected data: `is_model_valid(model, *random_data)`, .
    max_trials : int, optional
        Maximum number of iterations for random sample selection.
    stop_sample_num : int, optional
        Stop iteration if at least this number of inliers are found.
    stop_residuals_sum : float, optional
        Stop iteration if sum of residuals is less than or equal to this
        threshold.
    stop_probability : float, optional, in range [0, 1]
        RANSAC iteration stops if at least one outlier-free set of the
        training data is sampled with ``probability >= stop_probability``,
        depending on the current best model's inlier ratio and the number
        of trials. This requires to generate at least N samples (trials):

            N >= log(1 - probability) / log(1 - e**m)

        where the probability (confidence) is typically set to a high value
        such as 0.99, e is the current fraction of inliers w.r.t. the
        total number of samples, and m is the min_samples value.
    rng : {`numpy.random.Generator`, int}, optional
        Pseudo-random number generator.
        By default, a PCG64 generator is used (see :func:`numpy.random.default_rng`).
        If `rng` is an int, it is used to seed the generator.
    initial_inliers : array-like of bool, shape (N,), optional
        Initial samples selection for model estimation


    Returns
    -------
    model : object
        Best model with largest consensus set.
    inliers : (N,) array
        Boolean mask of inliers classified as ``True``.

    References
    ----------
    .. [1] "RANSAC", Wikipedia, https://en.wikipedia.org/wiki/RANSAC

    Examples
    --------

    Generate ellipse data without tilt and add noise:

    >>> t = np.linspace(0, 2 * np.pi, 50)
    >>> xc, yc = 20, 30
    >>> a, b = 5, 10
    >>> x = xc + a * np.cos(t)
    >>> y = yc + b * np.sin(t)
    >>> data = np.column_stack([x, y])
    >>> rng = np.random.default_rng(203560)  # do not copy this value
    >>> data += rng.normal(size=data.shape)

    Add some faulty data:

    >>> data[0] = (100, 100)
    >>> data[1] = (110, 120)
    >>> data[2] = (120, 130)
    >>> data[3] = (140, 130)

    Estimate ellipse model using all available data:

    >>> model = EllipseModel.from_estimate(data)
    >>> np.round(model.center)
    array([71., 75.])
    >>> np.round(model.axis_lengths)
    array([77., 13.])
    >>> np.round(model.theta)
    1.0

    Next we estimate an ellipse model using RANSAC.

    Note that the results are not deterministic, because the RANSAC algorithm
    uses some randomness.   If you need the results to be deterministic, pass a
    seeded number generator with the ``rng`` argument to ``ransac``.

    >>> ransac_model, inliers = ransac(data, EllipseModel, 20, 3, max_trials=50)
    >>> np.abs(np.round(ransac_model.center))  # doctest: +SKIP
    array([20., 30.])
    >>> np.abs(np.round(ransac_model.axis_lengths))  # doctest: +SKIP
    array([10., 6.])
    >>> np.abs(np.round(ransac_model.theta))    # doctest: +SKIP
    2.0
    >>> inliers  # doctest: +SKIP
    array([False, False, False, False,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True], dtype=bool)
    >>> sum(inliers) > 40
    True

    RANSAC can be used to robustly estimate a geometric
    transformation. In this section, we also show how to use a
    proportion of the total samples, rather than an absolute number.

    >>> from skimage.transform import SimilarityTransform
    >>> rng = np.random.default_rng()
    >>> src = 100 * rng.random((50, 2))
    >>> model0 = SimilarityTransform(scale=0.5, rotation=1,
    ...                              translation=(10, 20))
    >>> dst = model0(src)
    >>> dst[0] = (10000, 10000)
    >>> dst[1] = (-100, 100)
    >>> dst[2] = (50, 50)
    >>> ratio = 0.5  # use half of the samples
    >>> min_samples = int(ratio * len(src))
    >>> model, inliers = ransac(
    ...     (src, dst),
    ...     SimilarityTransform,
    ...     min_samples,
    ...     10,
    ...     initial_inliers=np.ones(len(src), dtype=bool),
    ... )  # doctest: +SKIP
    >>> inliers  # doctest: +SKIP
    array([False, False, False,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True])

    """
    ...

