"""
This type stub file was generated by pyright.
"""

from functools import cache

def dispatching_disabled() -> bool:
    """Determine if dispatching has been disabled by the user."""
    ...

def public_api_module(func) -> str:
    """Get the name of the public module for a scikit-image function.

    This computes the name of the public submodule in which the function can
    be found.
    """
    ...

@cache
def all_backends() -> dict[Any, Any]:
    """List all installed backends and information about them."""
    ...

def dispatchable(func) -> _Wrapped[..., Any, ..., Any]:
    """Mark a function as dispatchable.

    When a decorated function is called, the installed backends are
    searched for an implementation. If no backend implements the function
    then the scikit-image implementation is used.
    """
    ...

class BackendInformation:
    """Information about a backend

    A backend that wants to provide additional information about itself
    should return an instance of this from its information entry point.
    """
    def __init__(self, supported_functions) -> None:
        ...
    


class DispatchNotification(RuntimeWarning):
    """Notification issued when a function is dispatched to a backend."""
    ...


