"""
This type stub file was generated by pyright.
"""

__all__ = ['slice_along_axes']
def slice_along_axes(image, slices, axes=..., copy=...):
    """Slice an image along given axes.

    Parameters
    ----------
    image : ndarray
        Input image.
    slices : list of 2-tuple (a, b) where a < b.
        For each axis in `axes`, a corresponding 2-tuple
        ``(min_val, max_val)`` to slice with (as with Python slices,
        ``max_val`` is non-inclusive).
    axes : int or tuple, optional
        Axes corresponding to the limits given in `slices`. If None,
        axes are in ascending order, up to the length of `slices`.
    copy : bool, optional
        If True, ensure that the output is not a view of `image`.

    Returns
    -------
    out : ndarray
        The region of `image` corresponding to the given slices and axes.

    Examples
    --------
    >>> from skimage import data
    >>> img = data.camera()
    >>> img.shape
    (512, 512)
    >>> cropped_img = slice_along_axes(img, [(0, 100)])
    >>> cropped_img.shape
    (100, 512)
    >>> cropped_img = slice_along_axes(img, [(0, 100), (0, 100)])
    >>> cropped_img.shape
    (100, 100)
    >>> cropped_img = slice_along_axes(img, [(0, 100), (0, 75)], axes=[1, 0])
    >>> cropped_img.shape
    (75, 100)
    """
    ...

