"""
This type stub file was generated by pyright.
"""

@_rename_image_params
def compare_images(image0, image1, *, method=..., n_tiles=...) -> NDArray[Incomplete] | NDArray[float64] | NDArray[floating[Any]] | ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """
    Return an image showing the differences between two images.

    .. versionadded:: 0.16

    Parameters
    ----------
    image0, image1 : ndarray, shape (M, N)
        Images to process, must be of the same shape.

        .. versionchanged:: 0.24
            `image1` and `image2` were renamed into `image0` and `image1`
            respectively.
    method : {'diff', 'blend', 'checkerboard'}, optional
        Method used for the comparison.
        Details are provided in the note section.

        .. versionchanged:: 0.24
            This parameter and following ones are keyword-only.
    n_tiles : tuple, optional
        Used only for the `checkerboard` method. Specifies the number
        of tiles (row, column) to divide the image.

    Returns
    -------
    comparison : ndarray, shape (M, N)
        Image showing the differences.

    Notes
    -----
    ``'diff'`` computes the absolute difference between the two images.
    ``'blend'`` computes the mean value.
    ``'checkerboard'`` makes tiles of dimension `n_tiles` that display
    alternatively the first and the second image. Note that images must be
    2-dimensional to be compared with the checkerboard method.
    """
    ...

