"""
This type stub file was generated by pyright.
"""

__all__ = ['img_as_float32', 'img_as_float64', 'img_as_float', 'img_as_int', 'img_as_uint', 'img_as_ubyte', 'img_as_bool', 'dtype_limits']
_integer_types = ...
_integer_ranges = ...
dtype_range = ...
_supported_types = ...
def dtype_limits(image, clip_negative=...) -> tuple[bool | int, bool | int]:
    """Return intensity limits, i.e. (min, max) tuple, of the image's dtype.

    Parameters
    ----------
    image : ndarray
        Input image.
    clip_negative : bool, optional
        If True, clip the negative range (i.e. return 0 for min intensity)
        even if the image dtype allows negative values.

    Returns
    -------
    imin, imax : tuple
        Lower and upper intensity limits.
    """
    ...

def convert(image, dtype, force_copy=..., uniform=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    ...

if _convert.__doc__ is not None:
    ...
def img_as_float32(image, force_copy=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to single-precision (32-bit) floating point format.

    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.

    Returns
    -------
    out : ndarray of float32
        Output image.

    Notes
    -----
    The range of a floating point image is [0.0, 1.0] or [-1.0, 1.0] when
    converting from unsigned or signed datatypes, respectively.
    If the input image has a float type, intensity values are not modified
    and can be outside the ranges [0.0, 1.0] or [-1.0, 1.0].

    """
    ...

def img_as_float64(image, force_copy=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to double-precision (64-bit) floating point format.

    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.

    Returns
    -------
    out : ndarray of float64
        Output image.

    Notes
    -----
    The range of a floating point image is [0.0, 1.0] or [-1.0, 1.0] when
    converting from unsigned or signed datatypes, respectively.
    If the input image has a float type, intensity values are not modified
    and can be outside the ranges [0.0, 1.0] or [-1.0, 1.0].

    """
    ...

def img_as_float(image, force_copy=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to floating point format.

    This function is similar to `img_as_float64`, but will not convert
    lower-precision floating point arrays to `float64`.

    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.

    Returns
    -------
    out : ndarray of float
        Output image.

    Notes
    -----
    The range of a floating point image is [0.0, 1.0] or [-1.0, 1.0] when
    converting from unsigned or signed datatypes, respectively.
    If the input image has a float type, intensity values are not modified
    and can be outside the ranges [0.0, 1.0] or [-1.0, 1.0].

    """
    ...

def img_as_uint(image, force_copy=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to 16-bit unsigned integer format.

    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.

    Returns
    -------
    out : ndarray of uint16
        Output image.

    Notes
    -----
    Negative input values will be clipped.
    Positive values are scaled between 0 and 65535.

    """
    ...

def img_as_int(image, force_copy=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to 16-bit signed integer format.

    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.

    Returns
    -------
    out : ndarray of int16
        Output image.

    Notes
    -----
    The values are scaled between -32768 and 32767.
    If the input data-type is positive-only (e.g., uint8), then
    the output image will still only have positive values.

    """
    ...

def img_as_ubyte(image, force_copy=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to 8-bit unsigned integer format.

    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.

    Returns
    -------
    out : ndarray of ubyte (uint8)
        Output image.

    Notes
    -----
    Negative input values will be clipped.
    Positive values are scaled between 0 and 255.

    """
    ...

def img_as_bool(image, force_copy=...) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert an image to boolean format.

    Parameters
    ----------
    image : ndarray
        Input image.
    force_copy : bool, optional
        Force a copy of the data, irrespective of its current dtype.

    Returns
    -------
    out : ndarray of bool (`bool_`)
        Output image.

    Notes
    -----
    The upper half of the input dtype's positive range is True, and the lower
    half is False. All negative values (if present) are False.

    """
    ...

