"""
This type stub file was generated by pyright.
"""

from .version_requirements import require

__all__ = ['polygon_clip', 'polygon_area']
@require("matplotlib", ">=3.3")
def polygon_clip(rp, cp, r0, c0, r1, c1) -> tuple[Any, Any]:
    """Clip a polygon to the given bounding box.

    Parameters
    ----------
    rp, cp : (K,) ndarray of double
        Row and column coordinates of the polygon.
    (r0, c0), (r1, c1) : double
        Top-left and bottom-right coordinates of the bounding box.

    Returns
    -------
    r_clipped, c_clipped : (L,) ndarray of double
        Coordinates of clipped polygon.

    Notes
    -----
    This makes use of Sutherland-Hodgman clipping as implemented in
    AGG 2.4 and exposed in Matplotlib.

    """
    ...

def polygon_area(pr, pc) -> Any:
    """Compute the area of a polygon.

    Parameters
    ----------
    pr, pc : (K,) array of float
        Polygon row and column coordinates.

    Returns
    -------
    a : float
        Area of the polygon.
    """
    ...

