"""
This type stub file was generated by pyright.
"""

signed_integer_dtypes = ...
signed_integer_types = ...
unsigned_integer_dtypes = ...
integer_dtypes = ...
integer_types = ...
floating_dtypes = ...
floating_types = ...
complex_dtypes = ...
complex_types = ...
inexact_dtypes = ...
inexact_types = ...
bool_types = ...
numeric_dtypes = ...
numeric_types = ...
def numeric_dtype_min_max(dtype) -> tuple[Any, Any]:
    """Return minimum and maximum representable value for a given dtype.

    A convenient wrapper around `numpy.finfo` and `numpy.iinfo` that
    additionally supports numpy.bool as well.

    Parameters
    ----------
    dtype : numpy.dtype
        The dtype. Tries to convert Python "types" such as int or float, to
        the corresponding NumPy dtype.

    Returns
    -------
    min, max : number
        Minimum and maximum of the given `dtype`. These scalars are themselves
        of the given `dtype`.

    Examples
    --------
    >>> import numpy as np
    >>> numeric_dtype_min_max(np.uint8)
    (0, 255)
    >>> numeric_dtype_min_max(bool)
    (False, True)
    >>> numeric_dtype_min_max(np.float64)
    (-1.7976931348623157e+308, 1.7976931348623157e+308)
    >>> numeric_dtype_min_max(int)
    (-9223372036854775808, 9223372036854775807)
    """
    ...

