"""
This type stub file was generated by pyright.
"""

__all__ = ['deprecate_func', 'get_bound_method_class', 'all_warnings', 'safe_as_int', 'check_shape_equality', 'check_nD', 'warn', 'reshape_nd', 'identity', 'slice_at_axis', "deprecate_parameter", "DEPRECATED"]
def count_inner_wrappers(func) -> int:
    """Count the number of inner wrappers by unpacking ``__wrapped__``.

    If a wrapped function wraps another wrapped function, then we refer to the
    wrapping of the second function as an *inner wrapper*.

    For example, consider this code fragment:

    .. code-block:: python
        @wrap_outer
        @wrap_inner
        def foo():
            pass

    Here ``@wrap_inner`` applies a wrapper to ``foo``, and ``@wrap_outer``
    applies a wrapper to the result.

    Parameters
    ----------
    func : callable
        The callable of which to determine the number of inner wrappers.

    Returns
    -------
    count : int
        The number of times `func` has been wrapped.

    See Also
    --------
    count_global_wrappers
    """
    ...

def count_global_wrappers(func) -> int:
    """Count the total number of times a function as been wrapped globally.

    Similar to :func:`count_inner_wrappers`, this counts the number of times
    `func` has been wrapped. However, this function doesn't start counting
    from `func` but instead tries to access the "global representation" of
    `func`. This means that you could use this function from inside a wrapper
    that was applied first, and still count wrappers that were applied on
    top of it afterwards.

    E.g., `func` might be wrapped by multiple decorators that emit
    warnings. In that case, calling this function in the inner-most decorator
    will still return the total count of wrappers.

    Parameters
    ----------
    func : callable
        The callable of which to determine the number of wrappers. Can be a
        function or method of a class.

    Returns
    -------
    count : int
        The number of times `func` has been wrapped.

    See Also
    --------
    count_inner_wrappers
    """
    ...

class change_default_value:
    """Decorator for changing the default value of an argument.

    Parameters
    ----------
    arg_name : str
        The name of the argument to be updated.
    new_value : any
        The argument new value.
    changed_version : str
        The package version in which the change will be introduced.
    warning_msg : str
        Optional warning message. If None, a generic warning message
        is used.
    stacklevel : {None, int}, optional
        If None, the decorator attempts to detect the appropriate stacklevel for the
        deprecation warning automatically. This can fail, e.g., due to
        decorating a closure, in which case you can set the stacklevel manually
        here. The outermost decorator should have stacklevel 2, the next inner
        one stacklevel 3, etc.
    """
    def __init__(self, arg_name, *, new_value, changed_version, warning_msg=..., stacklevel=...) -> None:
        ...
    
    def __call__(self, func) -> _Wrapped[..., Any, ..., Any]:
        ...
    


class PatchClassRepr(type):
    """Control class representations in rendered signatures."""
    def __repr__(cls) -> str:
        ...
    


class DEPRECATED(metaclass=PatchClassRepr):
    """Signal value to help with deprecating parameters that use None.

    This is a proxy object, used to signal that a parameter has not been set.
    This is useful if ``None`` is already used for a different purpose or just
    to highlight a deprecated parameter in the signature.
    """
    ...


class deprecate_parameter:
    """Deprecate a parameter of a function.

    Parameters
    ----------
    deprecated_name : str
        The name of the deprecated parameter.
    start_version : str
        The package version in which the warning was introduced.
    stop_version : str
        The package version in which the warning will be replaced by
        an error / the deprecation is completed.
    template : str, optional
        If given, this message template is used instead of the default one.
    new_name : str, optional
        If given, the default message will recommend the new parameter name and an
        error will be raised if the user uses both old and new names for the
        same parameter.
    modify_docstring : bool, optional
        If the wrapped function has a docstring, add the deprecated parameters
        to the "Other Parameters" section.
    stacklevel : {None, int}, optional
        If None, the decorator attempts to detect the appropriate stacklevel for the
        deprecation warning automatically. This can fail, e.g., due to
        decorating a closure, in which case you can set the stacklevel manually
        here. The outermost decorator should have stacklevel 2, the next inner
        one stacklevel 3, etc.

    Notes
    -----
    Assign `DEPRECATED` as the new default value for the deprecated parameter.
    This marks the status of the parameter also in the signature and rendered
    HTML docs.

    This decorator can be stacked to deprecate more than one parameter.

    Examples
    --------
    >>> from skimage._shared.utils import deprecate_parameter, DEPRECATED
    >>> @deprecate_parameter(
    ...     "b", new_name="c", start_version="0.1", stop_version="0.3"
    ... )
    ... def foo(a, b=DEPRECATED, *, c=None):
    ...     return a, c

    Calling ``foo(1, b=2)``  will warn with::

        FutureWarning: Parameter `b` is deprecated since version 0.1 and will
        be removed in 0.3 (or later). To avoid this warning, please use the
        parameter `c` instead. For more details, see the documentation of
        `foo`.
    """
    DEPRECATED = DEPRECATED
    remove_parameter_template = ...
    replace_parameter_template = ...
    def __init__(self, deprecated_name, *, start_version, stop_version, template=..., new_name=..., modify_docstring=..., stacklevel=...) -> None:
        ...
    
    def __call__(self, func) -> _Wrapped[..., Any, ..., Any]:
        ...
    


class FailedEstimationAccessError(AttributeError):
    """Error from use of failed estimation instance

    This error arises from attempts to use an instance of
    :class:`FailedEstimation`.
    """
    ...


class FailedEstimation:
    """Class to indicate a failed transform estimation.

    The ``from_estimate`` class method of each transform type may return an
    instance of this class to indicate some failure in the estimation process.

    Parameters
    ----------
    message : str
        Message indicating reason for failed estimation.

    Attributes
    ----------
    message : str
        Message above.

    Raises
    ------
    FailedEstimationAccessError
        Exception raised for missing attributes or if the instance is used as a
        callable.
    """
    error_cls = FailedEstimationAccessError
    hint = ...
    def __init__(self, message) -> None:
        ...
    
    def __bool__(self) -> Literal[False]:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __call__(self, *args, **kwargs):
        ...
    
    def __getattr__(self, name):
        ...
    


class channel_as_last_axis:
    """Decorator for automatically making channels axis last for all arrays.

    This decorator reorders axes for compatibility with functions that only
    support channels along the last axis. After the function call is complete
    the channels axis is restored back to its original position.

    Parameters
    ----------
    channel_arg_positions : tuple of int, optional
        Positional arguments at the positions specified in this tuple are
        assumed to be multichannel arrays. The default is to assume only the
        first argument to the function is a multichannel array.
    channel_kwarg_names : tuple of str, optional
        A tuple containing the names of any keyword arguments corresponding to
        multichannel arrays.
    multichannel_output : bool, optional
        A boolean that should be True if the output of the function is not a
        multichannel array and False otherwise. This decorator does not
        currently support the general case of functions with multiple outputs
        where some or all are multichannel.

    """
    def __init__(self, channel_arg_positions=..., channel_kwarg_names=..., multichannel_output=...) -> None:
        ...
    
    def __call__(self, func) -> _Wrapped[..., Any, ..., Any]:
        ...
    


class deprecate_func:
    """Decorate a deprecated function and warn when it is called.

    Adapted from <http://wiki.python.org/moin/PythonDecoratorLibrary>.

    Parameters
    ----------
    deprecated_version : str
        The package version when the deprecation was introduced.
    removed_version : str
        The package version in which the deprecated function will be removed.
    hint : str, optional
        A hint on how to address this deprecation,
        e.g., "Use `skimage.submodule.alternative_func` instead."
    stacklevel :  {None, int}, optional
        If None, the decorator attempts to detect the appropriate stacklevel for the
        deprecation warning automatically. This can fail, e.g., due to
        decorating a closure, in which case you can set the stacklevel manually
        here. The outermost decorator should have stacklevel 2, the next inner
        one stacklevel 3, etc.

    Examples
    --------
    >>> @deprecate_func(
    ...     deprecated_version="1.0.0",
    ...     removed_version="1.2.0",
    ...     hint="Use `bar` instead."
    ... )
    ... def foo():
    ...     pass

    Calling ``foo`` will warn with::

        FutureWarning: `foo` is deprecated since version 1.0.0
        and will be removed in version 1.2.0. Use `bar` instead.
    """
    def __init__(self, *, deprecated_version, removed_version=..., hint=..., stacklevel=...) -> None:
        ...
    
    def __call__(self, func) -> _Wrapped[..., Any, ..., Any]:
        ...
    


def get_bound_method_class(m):
    """Return the class for a bound method."""
    ...

def safe_as_int(val, atol=...):
    """
    Attempt to safely cast values to integer format.

    Parameters
    ----------
    val : scalar or iterable of scalars
        Number or container of numbers which are intended to be interpreted as
        integers, e.g., for indexing purposes, but which may not carry integer
        type.
    atol : float
        Absolute tolerance away from nearest integer to consider values in
        ``val`` functionally integers.

    Returns
    -------
    val_int : NumPy scalar or ndarray of dtype `np.int64`
        Returns the input value(s) coerced to dtype `np.int64` assuming all
        were within ``atol`` of the nearest integer.

    Notes
    -----
    This operation calculates ``val`` modulo 1, which returns the mantissa of
    all values. Then all mantissas greater than 0.5 are subtracted from one.
    Finally, the absolute tolerance from zero is calculated. If it is less
    than ``atol`` for all value(s) in ``val``, they are rounded and returned
    in an integer array. Or, if ``val`` was a scalar, a NumPy scalar type is
    returned.

    If any value(s) are outside the specified tolerance, an informative error
    is raised.

    Examples
    --------
    >>> safe_as_int(7.0)
    7

    >>> safe_as_int([9, 4, 2.9999999999])
    array([9, 4, 3])

    >>> safe_as_int(53.1)
    Traceback (most recent call last):
        ...
    ValueError: Integer argument required but received 53.1, check inputs.

    >>> safe_as_int(53.01, atol=0.01)
    53

    """
    ...

def check_shape_equality(*images) -> None:
    """Check that all images have the same shape"""
    ...

def slice_at_axis(sl, axis):
    """
    Construct tuple of slices to slice an array in the given dimension.

    Parameters
    ----------
    sl : slice
        The slice for the given dimension.
    axis : int
        The axis to which `sl` is applied. All other dimensions are left
        "unsliced".

    Returns
    -------
    sl : tuple of slices
        A tuple with slices matching `shape` in length.

    Examples
    --------
    >>> slice_at_axis(slice(None, 3, -1), 1)
    (slice(None, None, None), slice(None, 3, -1), Ellipsis)
    """
    ...

def reshape_nd(arr, ndim, dim) -> _Array1D[Any]:
    """Reshape a 1D array to have n dimensions, all singletons but one.

    Parameters
    ----------
    arr : array, shape (N,)
        Input array
    ndim : int
        Number of desired dimensions of reshaped array.
    dim : int
        Which dimension/axis will not be singleton-sized.

    Returns
    -------
    arr_reshaped : array, shape ([1, ...], N, [1,...])
        View of `arr` reshaped to the desired shape.

    Examples
    --------
    >>> rng = np.random.default_rng()
    >>> arr = rng.random(7)
    >>> reshape_nd(arr, 2, 0).shape
    (7, 1)
    >>> reshape_nd(arr, 3, 1).shape
    (1, 7, 1)
    >>> reshape_nd(arr, 4, -1).shape
    (1, 1, 1, 7)
    """
    ...

def check_nD(array, ndim, arg_name=...) -> None:
    """
    Verify an array meets the desired ndims and array isn't empty.

    Parameters
    ----------
    array : array-like
        Input array to be validated
    ndim : int or iterable of ints
        Allowable ndim or ndims for the array.
    arg_name : str, optional
        The name of the array in the original function.

    """
    ...

def convert_to_float(image, preserve_range) -> ndarray[Any, Any] | NDArray[bool_] | ndarray[Any, _dtype] | ndarray[_AnyShape, _dtype] | ndarray[tuple[int], _dtype] | _Array[Any | tuple[int], Incomplete]:
    """Convert input image to float image with the appropriate range.

    Parameters
    ----------
    image : ndarray
        Input image.
    preserve_range : bool
        Determines if the range of the image should be kept or transformed
        using img_as_float. Also see
        https://scikit-image.org/docs/dev/user_guide/data_types.html

    Notes
    -----
    * Input images with `float32` data type are not upcast.

    Returns
    -------
    image : ndarray
        Transformed version of the input.

    """
    ...

new_float_type = ...
def identity(image, *args, **kwargs):
    """Returns the first argument unmodified."""
    ...

def as_binary_ndarray(array, *, variable_name) -> ndarray[Any, dtype[Any]]:
    """Return `array` as a numpy.ndarray of dtype bool.

    Raises
    ------
    ValueError:
        An error including the given `variable_name` if `array` can not be
        safely cast to a boolean array.
    """
    ...

