from __future__ import annotations

import glob
import json
import os
import sys

import numpy as np
import torch
import torch.nn as nn
import torchvision.models as tv_models


# 1. Satisfy FastAI's internal pickle references
def label_func(*args, **kwargs):
    pass


sys.modules["__main__"].label_func = label_func

try:
    from fastai.vision.all import PILImage, load_learner

    HAS_FASTAI = True
except ImportError:
    HAS_FASTAI = False

import onnx
import onnxruntime as ort


class FastaiConcatPool2d(nn.Module):
    """Pure PyTorch replica of FastAI's AdaptiveConcatPool2d."""

    def __init__(self):
        super().__init__()
        self.ap = nn.AdaptiveAvgPool2d((1, 1))
        self.mp = nn.AdaptiveMaxPool2d((1, 1))

    def forward(self, x):
        return torch.cat([self.ap(x), self.mp(x)], dim=1)


def build_pure_sequential_model(num_classes: int) -> nn.Sequential:
    """Replicates the exact top-level layer sequence generated by FastAI."""
    base_resnet = tv_models.resnet18(weights=None)

    backbone = nn.Sequential(
        base_resnet.conv1,
        base_resnet.bn1,
        base_resnet.relu,
        base_resnet.maxpool,
        base_resnet.layer1,
        base_resnet.layer2,
        base_resnet.layer3,
        base_resnet.layer4,
    )

    head = nn.Sequential(
        FastaiConcatPool2d(),  # Index 1.0
        nn.Flatten(start_dim=1),  # Index 1.1
        nn.BatchNorm1d(1024),  # Index 1.2
        nn.Dropout(p=0.25),  # Index 1.3
        nn.Linear(1024, 512, bias=False),  # Index 1.4
        nn.ReLU(inplace=True),  # Index 1.5
        nn.BatchNorm1d(512),  # Index 1.6
        nn.Dropout(p=0.5),  # Index 1.7
        nn.Linear(512, num_classes, bias=False),  # Index 1.8
    )

    return nn.Sequential(backbone, head)


def extract_metadata(learn) -> dict:
    """Extracts vocab, normalization stats, and input resolution from FastAI pipeline."""
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    input_size = None

    # 1. Extract Normalization Stats & Batch-level Resize (after_batch)
    for tfm in getattr(learn.dls, "after_batch", []):
        if hasattr(tfm, "mean") and hasattr(tfm, "std"):
            mean = tfm.mean.cpu().tolist()
            std = tfm.std.cpu().tolist()
        if hasattr(tfm, "size") and input_size is None:
            # size can be an int (224) or tuple (224, 224)
            sz = tfm.size
            input_size = [sz, sz] if isinstance(sz, int) else list(sz)

    # 2. Extract Item-level Resize (after_item, e.g. Resize or RandomResizedCrop)
    if input_size is None:
        for tfm in getattr(learn.dls, "after_item", []):
            if hasattr(tfm, "size"):
                sz = tfm.size
                input_size = [sz, sz] if isinstance(sz, int) else list(sz)
                break

    # 3. Fallback: Query a sample batch directly from DataLoader
    if input_size is None and hasattr(learn.dls, "one_batch"):
        try:
            xb, _ = learn.dls.one_batch()
            # xb shape is [batch_size, channels, height, width]
            input_size = [int(xb.shape[2]), int(xb.shape[3])]
        except Exception:
            pass

    # 4. Final safety fallback
    if input_size is None:
        input_size = [224, 224]

    # Extract Vocab
    vocab = list(learn.dls.vocab) if hasattr(learn.dls, "vocab") else []

    return {
        "vocab": vocab,
        "mean": mean,
        "std": std,
        "input_size": input_size,
    }


def convert_single_file_to_onnx(pkl_path: str, sample_img_path: str, output_dir: str):
    base_name = os.path.splitext(os.path.basename(pkl_path))[0]
    onnx_path = os.path.join(output_dir, f"{base_name}.onnx")
    meta_path = os.path.join(output_dir, f"{base_name}.json")

    print(f"\n--- Exporting to ONNX: {os.path.basename(pkl_path)} ---")

    # 1. Load original FastAI model
    learn = load_learner(pkl_path)
    metadata = extract_metadata(learn)
    num_classes = len(metadata["vocab"])
    print(f"[1/5] Loaded FastAI model with {num_classes} classes.")

    # 2. Build PyTorch model & transfer state dict
    pure_model = build_pure_sequential_model(num_classes=num_classes)
    pure_model.load_state_dict(learn.model.state_dict(), strict=True)
    pure_model.eval()
    pure_model.cpu()

    # 3. Extract sample preprocessed input tensor
    img_fastai = PILImage.create(sample_img_path)
    dl = learn.dls.test_dl([img_fastai])
    shared_input_tensor = dl.one_batch()[0].cpu().float()

    # FastAI / PyTorch baseline prediction
    with torch.no_grad():
        fastai_logits = pure_model(shared_input_tensor).numpy()

    # 4. Export to ONNX format
    dynamic_axes = {"input": {0: "batch_size"}, "output": {0: "batch_size"}}

    torch.onnx.export(
        pure_model,
        shared_input_tensor,
        onnx_path,
        export_params=True,
        opset_version=14,
        do_constant_folding=True,
        input_names=["input"],
        output_names=["output"],
        dynamic_axes=dynamic_axes,
    )
    print(f"✅ [2/5] Exported ONNX file to: {onnx_path}")

    # Save sidecar metadata JSON
    with open(meta_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"✅ [3/5] Saved metadata JSON to: {meta_path}")

    # Structural check
    onnx_model = onnx.load(onnx_path)
    onnx.checker.check_model(onnx_model)

    # 5. Verify numerical outputs with ONNX Runtime
    ort_session = ort.InferenceSession(onnx_path, providers=["CPUExecutionProvider"])
    ort_inputs = {ort_session.get_inputs()[0].name: shared_input_tensor.numpy()}
    ort_logits = ort_session.run(None, ort_inputs)[0]

    try:
        np.testing.assert_allclose(fastai_logits, ort_logits, rtol=1e-4, atol=1e-5)
        print("✅ [4/5] Verification passed: PyTorch and ONNX Runtime logits match.")
    except AssertionError as e:
        print("❌ [4/5] Output mismatch detected between FastAI and ONNX output.")
        raise e

    print(f"✨ [5/5] Export complete for {base_name}.onnx")


def batch_convert_folder_to_onnx(
    source_dir: str, sample_img_path: str, output_dir: str
):
    if not HAS_FASTAI:
        raise RuntimeError("FastAI environment must be active to run conversion.")
    if not os.path.exists(sample_img_path):
        raise FileNotFoundError(
            f"Missing sample verification image at: {sample_img_path}"
        )

    os.makedirs(output_dir, exist_ok=True)
    pkl_files = glob.glob(os.path.join(source_dir, "*.pkl"))

    if not pkl_files:
        print(f"⚠️ Zero .pkl files found inside: {source_dir}")
        return

    success_count = 0
    failed_models = []

    for pkl_path in pkl_files:
        try:
            convert_single_file_to_onnx(pkl_path, sample_img_path, output_dir)
            success_count += 1
        except Exception as err:
            failed_models.append((os.path.basename(pkl_path), str(err)))

    print("\n==================================================")
    print(f"🏁 Process Completed. Passed: {success_count}/{len(pkl_files)}")
    if failed_models:
        for name, reason in failed_models:
            print(f" ❌ {name}: {reason}")
        raise RuntimeError("ONNX export failures detected.")


if __name__ == "__main__":
    batch_convert_folder_to_onnx(
        source_dir="/app/models",
        sample_img_path="/app/models/test_xray.png",
        output_dir="/app/models",
    )
