"""
This type stub file was generated by pyright.
"""

from .deconvolution import richardson_lucy, unsupervised_wiener, wiener
from .unwrap import unwrap_phase
from ._denoise import denoise_bilateral, denoise_tv_bregman, denoise_tv_chambolle, denoise_wavelet, estimate_sigma
from ._cycle_spin import cycle_spin
from .non_local_means import denoise_nl_means
from .inpaint import inpaint_biharmonic
from .j_invariant import calibrate_denoiser, denoise_invariant
from ._rolling_ball import ball_kernel, ellipsoid_kernel, rolling_ball

__all__ = ['wiener', 'unsupervised_wiener', 'richardson_lucy', 'unwrap_phase', 'denoise_tv_bregman', 'denoise_tv_chambolle', 'denoise_bilateral', 'denoise_wavelet', 'denoise_nl_means', 'denoise_invariant', 'estimate_sigma', 'inpaint_biharmonic', 'cycle_spin', 'calibrate_denoiser', 'rolling_ball', 'ellipsoid_kernel', 'ball_kernel']
